- id: remove-comments-from-jsonc
  name: Remove comments from jsonc
  description: Remove // comments from jsonc file and save it as json file.
  language: python
  entry: remove_jsonc_comments
  require_serial: true
  files: '.*\.jsonc'
- id: ruler
  name: Add ruler comment
  description: Add ruler comment to commit message template
  language: python
  entry: add_commit_msg_ruler_comment
  stages: [prepare-commit-msg]
